   public class Datatypes {
     public static void main(String[] args) {

        boolean b= true;
        char ch = 'B';
         int a=123;
         byte by= 123;  
         double d=123.12;
         float f=123.12f;

        // Non-primitive datatype which is String,array,classes 

        String str="Ashirwad"; // always S is capital in String 
        int arr[]= {10,20,30,40};
        System.out.println(arr[1]);
System.out.println(b);
System.out.println(ch);
System.out.println(a);
System.out.println(by);
System.out.println(d);
System.out.println(f);
System.out.println(str);


    }
    
}
